### ISSUE TITLE
x50a pins

### ISSUE THREAD

**Issue by Poopikakas** [Sonic-Amiga/ESP8266-Faikin#11]
Hi, is there a pinout description for the esp8266 regarding the x50a cable.

**Comment by Sonic-Amiga** [comment]
Hi! Sorry for so-o-o-o delayed reply.
Unfortunately i don't have any info about cables; frankly speaking i have never seen x50a A/C. You may ask here https://github.com/revk/ESP32-Faikin

**Comment by Sonic-Amiga** [comment]
Recently i've acquired a BRP069C41 controller, which is designed for X50 protocol. Here are photos of AC-side connectors and their pins:
![X50-annotated](https://github.com/user-attachments/assets/dec17f65-2082-455b-90c9-35a87138fe74)
![X50-bottom](https://github.com/user-attachments/assets/054724d5-f43a-4b9f-9f86-24965f701e09)

**Comment by Sonic-Amiga** [comment]
I hope this answers the question. Please reopen if required
