### ISSUE TITLE
Confuses Auto vs Quiet modes

### ISSUE THREAD

**Issue by Sonic-Amiga** [Sonic-Amiga/ESP8266-Faikin#4]
In both cases (when activated by RC) Faikin reports fan speed selector as "auto".
Setting these modes also needs verification

**Comment by revk** [comment]
Good luck with that, I failed to find any indication of a difference if what comes from the a/c.

**Comment by Sonic-Amiga** [comment]
@revk Just verified on my older ATX20K "Siesta" with original Daikin BRP controller; everything is good, a proper f_rate is reported. So it's possible. Perhaps your AC, on which you tested that, is buggy. Its firmware authors are also mere humans after all.

**Comment by revk** [comment]
I am pretty sure my old Daikin worked too, in terms of f_rate, but I have yet to find the underlying S21 message for this.

**Comment by Sonic-Amiga** [comment]
The issue still persists. I managed to order an original BRP box from old stock, should arrive here in a week, so i'll be able to experiment.

**Comment by Sonic-Amiga** [comment]
Solved by today's commits.
