### ISSUE TITLE
What is the difference?

### ISSUE THREAD

**Issue by Glinka65** [Sonic-Amiga/ESP8266-Faikin#8]
What is the difference between "Pico", "Solo" and just S1?
If I understand correctly, these are compiled projects for loading into the ESP8266.
Downloaded S1 but didn't find Faikin XXXXXXXXXX wifi hotspot.
In order for the project to work, the ESP8266 needs a UART connection with the air conditioner or can the wifi point work separately?

**Comment by Sonic-Amiga** [comment]
Hello! Sorry for long delay. I missed open issues. These binaries came from original esp32 version, i overlooked and forgot to remove them. Now fixed. You need to build from source
